name: Deploy repository to Github Pages

on:
  push:
    paths:
      - "scrapers/**"
    branches:
      - main
      - dev 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: "0"

      - run: |
          chmod +x build_site.sh
          ./build_site.sh _site/${{ github.ref_name }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site/${{ github.ref_name }}
          destination_dir: ${{ github.ref_name }}
          keep_files: true
